"""
Loads and queries the allowlist YAML generated by Django's
``generate_agent_allowlist`` management command.
"""

from __future__ import annotations

from pathlib import Path

import yaml


class Allowlist:
    """In-memory representation of the agent column allowlist."""

    def __init__(
        self,
        tables: dict[str, dict[str, dict]],
        allowed_functions: set[str],
    ):
        # tables: {table_name: {column_name: {type, placeholder}}}
        self._tables = tables
        self._allowed_functions = allowed_functions

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    @classmethod
    def from_yaml(cls, path: str | Path) -> Allowlist:
        """Load an allowlist from a YAML file."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"Allowlist not found: {path}")

        with open(path) as f:
            data = yaml.safe_load(f)

        if not data or "tables" not in data:
            raise ValueError(f"Invalid allowlist YAML: missing 'tables' key in {path}")

        tables: dict[str, dict[str, dict]] = {}
        for table_name, table_info in data["tables"].items():
            columns = {}
            if table_info and "columns" in table_info:
                for col_name, col_info in table_info["columns"].items():
                    columns[col_name] = {
                        "type": col_info.get("type", "text"),
                        "placeholder": col_info.get("placeholder", "'[REDACTED]'"),
                    }
            tables[table_name] = columns

        funcs = set()
        for fn in data.get("allowed_functions", []):
            funcs.add(fn.upper())

        return cls(tables=tables, allowed_functions=funcs)

    # ------------------------------------------------------------------
    # Querying
    # ------------------------------------------------------------------

    def has_table(self, table: str) -> bool:
        """Return True if the table is known (in any app)."""
        return table.lower() in self._tables

    def is_column_visible(self, table: str, column: str) -> bool:
        """Return True if the column is on the allowlist for this table."""
        table_cols = self._tables.get(table.lower(), {})
        return column.lower() in table_cols

    def get_placeholder(self, table: str, column: str) -> str:
        """Return the type-preserving placeholder for a hidden column."""
        table_cols = self._tables.get(table.lower(), {})
        col_info = table_cols.get(column.lower())
        if col_info:
            return col_info["placeholder"]
        # Default placeholder for unknown columns
        return "'[REDACTED]'"

    def get_visible_columns(self, table: str) -> set[str]:
        """Return the set of visible column names for a table."""
        return set(self._tables.get(table.lower(), {}).keys())

    def is_function_allowed(self, func_name: str) -> bool:
        """Return True if the function is on the allowed list."""
        return func_name.upper() in self._allowed_functions

    @property
    def all_tables(self) -> set[str]:
        """Return all known table names."""
        return set(self._tables.keys())

    @property
    def allowed_functions(self) -> set[str]:
        return self._allowed_functions
